# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/devel/opencv/appsrc/libsrc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/devel/opencv/appsrc/libsrc

# Include any dependencies generated for this target.
include CMakeFiles/../lib/utility.lib.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../lib/utility.lib.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../lib/utility.lib.dir/flags.make

CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o: CMakeFiles/../lib/utility.lib.dir/flags.make
CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o: imageWindow.cc
	$(CMAKE_COMMAND) -E cmake_progress_report /home/devel/opencv/appsrc/libsrc/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o -c /home/devel/opencv/appsrc/libsrc/imageWindow.cc

CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/devel/opencv/appsrc/libsrc/imageWindow.cc > CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.i

CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/devel/opencv/appsrc/libsrc/imageWindow.cc -o CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.s

CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.requires:
.PHONY : CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.requires

CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.provides: CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.requires
	$(MAKE) -f CMakeFiles/../lib/utility.lib.dir/build.make CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.provides.build
.PHONY : CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.provides

CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.provides.build: CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o

CMakeFiles/../lib/utility.lib.dir/utility.cc.o: CMakeFiles/../lib/utility.lib.dir/flags.make
CMakeFiles/../lib/utility.lib.dir/utility.cc.o: utility.cc
	$(CMAKE_COMMAND) -E cmake_progress_report /home/devel/opencv/appsrc/libsrc/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building CXX object CMakeFiles/../lib/utility.lib.dir/utility.cc.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_FLAGS) -o CMakeFiles/../lib/utility.lib.dir/utility.cc.o -c /home/devel/opencv/appsrc/libsrc/utility.cc

CMakeFiles/../lib/utility.lib.dir/utility.cc.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../lib/utility.lib.dir/utility.cc.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -E /home/devel/opencv/appsrc/libsrc/utility.cc > CMakeFiles/../lib/utility.lib.dir/utility.cc.i

CMakeFiles/../lib/utility.lib.dir/utility.cc.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../lib/utility.lib.dir/utility.cc.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_FLAGS) -S /home/devel/opencv/appsrc/libsrc/utility.cc -o CMakeFiles/../lib/utility.lib.dir/utility.cc.s

CMakeFiles/../lib/utility.lib.dir/utility.cc.o.requires:
.PHONY : CMakeFiles/../lib/utility.lib.dir/utility.cc.o.requires

CMakeFiles/../lib/utility.lib.dir/utility.cc.o.provides: CMakeFiles/../lib/utility.lib.dir/utility.cc.o.requires
	$(MAKE) -f CMakeFiles/../lib/utility.lib.dir/build.make CMakeFiles/../lib/utility.lib.dir/utility.cc.o.provides.build
.PHONY : CMakeFiles/../lib/utility.lib.dir/utility.cc.o.provides

CMakeFiles/../lib/utility.lib.dir/utility.cc.o.provides.build: CMakeFiles/../lib/utility.lib.dir/utility.cc.o

# Object files for target ../lib/utility.lib
__/lib/utility_lib_OBJECTS = \
"CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o" \
"CMakeFiles/../lib/utility.lib.dir/utility.cc.o"

# External object files for target ../lib/utility.lib
__/lib/utility_lib_EXTERNAL_OBJECTS =

lib../lib/utility.lib.a: CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o
lib../lib/utility.lib.a: CMakeFiles/../lib/utility.lib.dir/utility.cc.o
lib../lib/utility.lib.a: CMakeFiles/../lib/utility.lib.dir/build.make
lib../lib/utility.lib.a: CMakeFiles/../lib/utility.lib.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking CXX static library lib../lib/utility.lib.a"
	$(CMAKE_COMMAND) -P CMakeFiles/../lib/utility.lib.dir/cmake_clean_target.cmake
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../lib/utility.lib.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../lib/utility.lib.dir/build: lib../lib/utility.lib.a
.PHONY : CMakeFiles/../lib/utility.lib.dir/build

CMakeFiles/../lib/utility.lib.dir/requires: CMakeFiles/../lib/utility.lib.dir/imageWindow.cc.o.requires
CMakeFiles/../lib/utility.lib.dir/requires: CMakeFiles/../lib/utility.lib.dir/utility.cc.o.requires
.PHONY : CMakeFiles/../lib/utility.lib.dir/requires

CMakeFiles/../lib/utility.lib.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../lib/utility.lib.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../lib/utility.lib.dir/clean

CMakeFiles/../lib/utility.lib.dir/depend:
	cd /home/devel/opencv/appsrc/libsrc && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/devel/opencv/appsrc/libsrc /home/devel/opencv/appsrc/libsrc /home/devel/opencv/appsrc/libsrc /home/devel/opencv/appsrc/libsrc /home/devel/opencv/appsrc/libsrc/lib/utility.lib.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../lib/utility.lib.dir/depend

