# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# compile CXX with /usr/bin/c++
CXX_FLAGS = -I/home/devel/opencv/compiled/include -I/home/devel/opencv/compiled/include/opencv -I/home/devel/opencv/appsrc/libsrc/../include   

CXX_DEFINES = 

